# Generated by Django 5.2.4 on 2025-07-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
